.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH CMAKE SECTION "November 28, 2001"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
cmake \- Cross-platform Make
.SH SYNOPSIS
.B cmake
.RI [ options ] " files" ...
.br
.B CMakeSetup
.RI [ options ] " files" ...
.br
.B ctest
.RI [ options ] " files" ...
.SH DESCRIPTION
This manual page documents briefly the
.B cmake
and
.B CMakeSetup
and
.B ctest
commands.
This manual page was written for the Debian GNU/Linux distribution
because the original program does not have a manual page.
Instead, it has documentation in PDF format; see below.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.
\fBcmake\fP is a program that...
.SH OPTIONS
These programs follow the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
For a complete description, see the Info files.
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-v, \-\-version
Show version of program.
.SH SEE ALSO
.BR Dart (1),
.BR VTK (1).
.br
The programs are documented fully by
.IR /usr/share/doc/cmake/CMake.pdf.gz ,
installed with this package.
.SH AUTHOR
This manual page was written by A. Maitland Bottoms <bottoms@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
